### ISSUE TITLE
Document iTerm2 Profiles

### ISSUE THREAD

**Issue by parkr** [parkr/dotfiles#2]
I was just setting up my new :octocat: laptop and am already missing my iTerm2 profile. I am verrrrrrry fond of its gracious beauty. It should be saved here.
- [ ] Font https://github.com/caskroom/homebrew-fonts/issues/435 and addition to Brewfile
- [x] Colors
- [x] Font size must be done manually :( but documented

**Comment by pengwynn** [comment]
Hiya @parkr. :wave: Some drive by thoughts from a fellow iTerm user who just rebuilt his dev machine...

- Definitely store your [iTerm plist](https://github.com/pengwynn/dotfiles/blob/master/iterm/com.googlecode.iterm2.plist).
- Consider adding [base16-shell](https://github.com/chriskempson/base16-shell) to your path and managing your colors via those shell scripts instead of adding them all as iTerm profiles.
- Let [homebrew cask manage your fonts](https://github.com/pengwynn/dotfiles/blob/4d06f8a6c510dbb95bc78ae4780ff0253dc4b29b/homebrew/Brewfile#L52-L65) with `brew bundle`.

**Comment by parkr** [comment]
Hey, @pengwynn!!! Thanks for the ProTips :tm: :heart: 

Added the itermcolors profile in 375b7c03df00d96700a7ed32e051fd18c4b91f64.

> Consider adding base16-shell to your path and managing your colors via those shell scripts instead of adding them all as iTerm profiles.

As I make edits, I simply re-import them via Preferences > Profiles > Colors > Color Presets... > Import... ? What does your workflow look like for that?

> Let homebrew cask manage your fonts with brew bundle.

Oooooh, this is so cool. Do you generate that file by hand and run `brew bundle` each time it's edited?

**Comment by pengwynn** [comment]
>  I simply re-import them via Preferences > Profiles > Colors > Color Presets... > Import...

I was doing that. Switching to base16-shell as a submodule let me skip that step and change the color scheme from the command line. 

> Do you generate that file by hand and run brew bundle each time it's edited?

On this latest rebuild, I've tried to keep my setup scriptable by not installing anything by hand that I could otherwise script. So when there's a new app I want to install, I look for a brew package or a cask and add that to the Brewfile and then `brew bundle`. Automating fonts as part of that has been amazing. No more futzing with FontBook.

**Comment by parkr** [comment]
Copied into https://github.com/fnichols/macosx-iterm2-settings to https://github.com/parkr/dotfiles/tree/master/iterm and will be using that to install iTerm2 profiles & settings. ✨
